version: '3.7'
services:
  # web:
  #   build: ./
  #   command: >
  #     bash -c "python manage.py migrate
  #     && python manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tenderhack
      - POSTGRES_DB=tenderhack_dev
    ports:
      - 5432:5432
  # bot:
  #   build: ./
  #   command: python run_bot.py
  #   env_file:
  #     - ./.env.dev
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  postgres_data: