# Generated by Django 3.2.9 on 2021-11-12 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('conclusion_date', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_inn', models.BigIntegerField(max_length=12)),
                ('customer_kpp', models.BigIntegerField(max_length=9)),
                ('customer_name', models.CharField(max_length=255)),
                ('provider_inn', models.BigIntegerField(max_length=12)),
                ('provider_kpp', models.BigIntegerField(max_length=9)),
                ('provider_name', models.CharField(max_length=255)),
                ('stu', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='STU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=20)),
                ('specifications', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
