# Generated by Django 3.2.9 on 2021-11-12 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(default=uuid.UUID('b5232073-401b-470a-abe5-b71264dbf5a4'), max_length=255, unique=True),
        ),
    ]
