# Generated by Django 3.2.9 on 2021-11-13 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211112_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('d4a2385c-c6d0-4507-9318-8d0fd0cb780e'), max_length=255, unique=True),
        ),
    ]
