# Generated by Django 3.2.9 on 2021-11-13 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('13e2c090-1660-4335-91bc-ca0fd7a205fa'), max_length=255, unique=True),
        ),
    ]
