# Generated by Django 3.2.9 on 2021-11-13 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('ccb3db44-24f0-48c4-ba75-a48e1b4f1796'), max_length=255, unique=True),
        ),
    ]
