# Generated by Django 3.2.9 on 2021-11-13 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('935429d1-8fd9-4c40-9367-0e3c45736627'), max_length=255, unique=True),
        ),
    ]
