# Generated by Django 3.2.9 on 2021-11-13 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('30afa072-bbcc-497e-af3f-9c1a82af768c'), max_length=255, unique=True),
        ),
    ]
