# Generated by Django 3.2.9 on 2021-11-13 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('df362cd8-18d7-4669-86ad-aa6a84e6b34b'), max_length=255, unique=True),
        ),
    ]
