# Generated by Django 3.2.9 on 2021-11-13 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('1e562146-70df-48fa-81cd-381dbf88a4d4'), max_length=255, unique=True),
        ),
    ]
