# Generated by Django 3.2.9 on 2021-11-13 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('da648b8f-8cf0-4ba0-a3fc-47a83cc06d53'), max_length=255, unique=True),
        ),
    ]
