# Generated by Django 3.2.9 on 2021-11-13 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('f09d0dfe-95b7-4589-ad5c-c27084b144fd'), max_length=255, unique=True),
        ),
    ]
