# Generated by Django 3.2.9 on 2021-11-13 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('dda5140e-716a-4509-90f5-3e82d31c0bf9'), max_length=255, unique=True),
        ),
    ]
