# Generated by Django 3.2.9 on 2021-11-13 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('3a3c4f75-c3dc-423b-b04d-eb526f5d0644'), max_length=255, unique=True),
        ),
    ]
