# Generated by Django 3.2.9 on 2021-11-13 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('e99149e4-6bbd-4d59-b355-ce4f0d6fbfcd'), max_length=255, unique=True),
        ),
    ]
