# Generated by Django 3.2.9 on 2021-11-13 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('46e9d047-7cce-49b5-b31f-43a169829e40'), max_length=255, unique=True),
        ),
    ]
