# Generated by Django 3.2.9 on 2021-11-13 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('49d5ff34-62d2-44c8-a762-7e6f0e87c0b8'), max_length=255, unique=True),
        ),
    ]
