# Generated by Django 3.2.9 on 2021-11-13 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_inn',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_kpp',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('de47948d-31f3-405c-b0b0-571d71cd271a'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_inn',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_kpp',
            field=models.IntegerField(max_length=9),
        ),
    ]
