# Generated by Django 3.2.9 on 2021-11-13 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211113_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_inn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_kpp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('d02a2436-fcc8-41d3-8a8e-336a27a48c12'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_inn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_kpp',
            field=models.IntegerField(),
        ),
    ]
