# Generated by Django 3.2.9 on 2021-11-13 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211113_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('73c6bdb9-d467-4139-9eda-58e0518746c7'), max_length=255, unique=True),
        ),
    ]
