# Generated by Django 3.2.9 on 2021-11-13 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('c4955497-5964-459b-b008-090a46378bc5'), max_length=255, unique=True),
        ),
    ]
