# Generated by Django 3.2.9 on 2021-11-13 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('de1659c9-0097-4678-92e3-119736096c0c'), max_length=255, unique=True),
        ),
    ]
