# Generated by Django 3.2.9 on 2021-11-13 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('bcc30044-730e-4180-8245-c22a81a42637'), max_length=255, unique=True),
        ),
    ]
