# Generated by Django 3.2.9 on 2021-11-13 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('a6c8d175-4fb0-4697-a375-73a57ea4f1a6'), max_length=255, unique=True),
        ),
    ]
