# Generated by Django 3.2.9 on 2021-11-13 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('8d1d5fd0-b338-49a9-bf92-7cea0f7eddc1'), max_length=255, unique=True),
        ),
    ]
