# Generated by Django 3.2.9 on 2021-11-13 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('5bdaee87-46d8-4602-b19c-0380d2314098'), max_length=255, unique=True),
        ),
    ]
