# Generated by Django 3.2.9 on 2021-11-13 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('ff1e418b-c341-4926-a1a1-27f77a346c36'), max_length=255, unique=True),
        ),
    ]
