# Generated by Django 3.2.9 on 2021-11-13 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('91f6a913-87cb-4e7e-bc1d-333b5aabad8d'), max_length=255, unique=True),
        ),
    ]
