# Generated by Django 3.2.9 on 2021-11-13 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('24e46b02-f44d-4c66-ae4d-8a8843447bc4'), max_length=255, unique=True),
        ),
    ]
