# Generated by Django 3.2.9 on 2021-11-13 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('7bb36d48-7eae-49e1-b153-499154686644'), max_length=255, unique=True),
        ),
    ]
