# Generated by Django 3.2.9 on 2021-11-13 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('b4b90af1-3ebc-4323-a9a5-82dd2cca282d'), max_length=255, unique=True),
        ),
    ]
