# Generated by Django 3.2.9 on 2021-11-13 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('0f15b40b-765e-4c6c-b4ec-d5e716688108'), max_length=255, unique=True),
        ),
    ]
