# Generated by Django 3.2.9 on 2021-11-13 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('bca15f7d-f4d1-455f-9214-a6e1b592e3cb'), max_length=255, unique=True),
        ),
    ]
