# Generated by Django 3.2.9 on 2021-11-13 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('cadb9e62-5ddb-48f4-badc-b6b3679a7c1c'), max_length=255, unique=True),
        ),
    ]
