# Generated by Django 3.2.9 on 2021-11-13 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('2799086d-b422-4212-afab-c6a69d0a4c6c'), max_length=255, unique=True),
        ),
    ]
