# Generated by Django 3.2.9 on 2021-11-13 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('a449eb18-c680-4be9-9e6b-696bdd5321d6'), max_length=255, unique=True),
        ),
    ]
