# Generated by Django 3.2.9 on 2021-11-13 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('8f6dc512-ddfe-4393-89db-6a0cdfd963fb'), max_length=255, unique=True),
        ),
    ]
