# Generated by Django 3.2.9 on 2021-11-13 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('b7c9fdef-a934-4fdc-a39e-b89d1192f582'), max_length=255, unique=True),
        ),
    ]
