# Generated by Django 3.2.9 on 2021-11-13 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('f8820e14-3715-45b2-aff8-0623772a958b'), max_length=255, unique=True),
        ),
    ]
