# Generated by Django 3.2.9 on 2021-11-13 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('b726bba9-ca75-466b-97dc-ffa74640774a'), max_length=255, unique=True),
        ),
    ]
