# Generated by Django 3.2.9 on 2021-11-13 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('a7797df7-0bc4-4d80-924b-a3f90db6cee2'), max_length=255, unique=True),
        ),
    ]
