# Generated by Django 3.2.9 on 2021-11-13 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('9bc4757e-5225-4c6b-9b6f-2d75212d90de'), max_length=255, unique=True),
        ),
    ]
