# Generated by Django 3.2.9 on 2021-11-13 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('ec3e15b3-340f-4359-bb4a-ace906499d44'), max_length=255, unique=True),
        ),
    ]
