# Generated by Django 3.2.9 on 2021-11-13 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('6a10dc8f-926d-4b37-b3b3-27d1cadd98a5'), max_length=255, unique=True),
        ),
    ]
