# Generated by Django 3.2.9 on 2021-11-13 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('33c20a7e-0668-436a-b083-8d92ff28caac'), max_length=255, unique=True),
        ),
    ]
