# Generated by Django 3.2.9 on 2021-11-13 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('57f44853-3758-4aed-affb-09baed963741'), max_length=255, unique=True),
        ),
    ]
