# Generated by Django 3.2.9 on 2021-11-13 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('cba8d70c-141d-4eb2-bfac-7fd10d357a16'), max_length=255, unique=True),
        ),
    ]
