# Generated by Django 3.2.9 on 2021-11-13 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('8805c6ee-8668-4826-812d-a803b08fb6f7'), max_length=255, unique=True),
        ),
    ]
