# Generated by Django 3.2.9 on 2021-11-13 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('4635f78e-1510-4525-8cd0-83360bd9540c'), max_length=255, unique=True),
        ),
    ]
