# Generated by Django 3.2.9 on 2021-11-13 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('f3920bf6-75a6-431d-863a-64ac11895f23'), max_length=255, unique=True),
        ),
    ]
