# Generated by Django 3.2.9 on 2021-11-13 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('b8359dc4-59c2-4cb3-974d-9dd360319e07'), max_length=255, unique=True),
        ),
    ]
