# Generated by Django 3.2.9 on 2021-11-13 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('1b5444d9-6ec9-4a84-955a-bc23061fbf48'), max_length=255, unique=True),
        ),
    ]
