# Generated by Django 3.2.9 on 2021-11-13 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('bff568ba-0d16-4ca8-beb3-57fb667d1ab6'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stu',
            name='code',
            field=models.CharField(max_length=25),
        ),
    ]
