# Generated by Django 3.2.9 on 2021-11-13 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20211114_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='conclusion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('90cdce94-d12c-4f93-b5d0-fb818b1956d4'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
