# Generated by Django 3.2.9 on 2021-11-13 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20211114_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('8a871964-98f7-4cf5-bb05-dde3fedb44d8'), max_length=255, unique=True),
        ),
    ]
