# Generated by Django 3.2.9 on 2021-11-13 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20211114_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_inn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_kpp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('bdd16547-f97d-4b7e-be6a-8f2885ad9d51'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_inn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_kpp',
            field=models.BigIntegerField(),
        ),
    ]
