# Generated by Django 3.2.9 on 2021-11-14 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20211114_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_inn',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_kpp',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('8fba7466-4309-4d3a-a10e-9e5da8094afd'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_inn',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_kpp',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
