# Generated by Django 3.2.9 on 2021-11-14 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20211114_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('beded3b3-924c-436a-967a-11402261c58e'), max_length=255, unique=True, verbose_name='Номер контракта'),
        ),
    ]
