# Generated by Django 3.2.9 on 2021-11-14 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.TextField(default=uuid.UUID('138a279c-7f6c-4d7d-b814-f579da3c7203'), max_length=255, unique=True, verbose_name='Номер контракта'),
        ),
    ]
